[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
monitor_echo = yes

board_build.embed_txtfiles =
    src/certs/AmazonRootCA.pem
    src/certs/certificate.pem.crt
    src/certs/private.pem.key